base: 'http://local.m-tel:8080/'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: German
    hreflang: de-de
    direction: ltr
    flag: de
    websiteTitle: ''
rootPageId: 1
websiteTitle: 'M Tel'
